# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# script_projet.py
# Created on: 2016-10-03 17:49:12.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: Comparaison d’images de statistiques
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

#Vérifie la license spatial analyst et ecrase dossier
arcpy.CheckOutExtension("Spatial")
arcpy.env.overwriteOutput = True

# Import os et datetime
import os
import datetime

#dossier avec les fichiers
dossier_sortie=os.path.normpath("C:\\Mini-Projet\mini_projet6") #chemin d'acces de mon dossier de fichiers
listef=os.listdir(dossier_sortie) # je cree une liste des fichiers dans le dossier
dossier_temp=os.path.normpath("C:\\Users\\Colette\\Documents\\ArcGIS\\Default1.gdb")

# définition chemin acces variables:
moyenne_3_3 = dossier_sortie+"\\moyenne_3_3"
moyenne_5_5 = dossier_sortie+"\\moyenne_5_5"
ecartype_5_5 = dossier_sortie+"\\ecartype_5_5"
Geodatabase = "C:\\Mini-Projet\\New_Personal_Geodatabase.mdb"
image_sortie = dossier_sortie #j'indique l'emplacement du fichier de sortie
temp1=dossier_temp+"\\"+"temp1"
temp2=dossier_temp+"\\"+"temp2"



for image_temp in listef:
        ext=image_temp[-4:] ##je recupere l'extension pour etre sûr qu'on traite une image
        date=image_temp[5:15]#je recupere les caractères qui constituent la date
        if ext =='.tif': 
                try:
                        D=datetime.datetime.strptime(date, '%Y-%m-%d')#je verifie que la date a bien le bon format
                except ValueError:
                        continue #si mauvais format, on passe au fichier suivant
                
        else:
                continue #permet de verifier qu'on a bien une image puis passe au fichier suivant si non

        D=datetime.datetime.strptime(date, '%Y-%m-%d')
        
        if D.month==5 or D.month==9:#on sélectionne les images des mois de mai et septembre
                print(image_temp)
                image=os.path.join(dossier_sortie, image_temp)#image_temp est le nom du fichier image et image est le chemin d'acces
                
                # Process: Focal Statistics Mean 3/3 //calculer moyenne locale fenetre 3*3
                arcpy.gp.FocalStatistics_sa(image, temp1, "Rectangle 3 3 CELL", "MEAN", "DATA")
                # Process: Copy Raster // changer la valeur des bits
                arcpy.CopyRaster_management(temp1, temp2, "", "", "-3,402823e+038", "NONE", "NONE", "8_BIT_UNSIGNED", "NONE", "NONE", "GRID", "NONE")
                # Process: Shift // translation
                arcpy.Shift_management(temp2, moyenne_3_3, "9", "0", "")
                print('calcul de la moyenne en fenetre 3*3: OK')
                        
                # Process: Focal Statistics Mean 5/5
                mean5_5=arcpy.gp.FocalStatistics_sa(image, temp1, "Rectangle 5 5 CELL", "MEAN", "DATA")
                # Process: Copy Raster (2)
                arcpy.CopyRaster_management(temp1, temp2, "", "", "-3,402823e+038", "NONE", "NONE", "8_BIT_UNSIGNED", "NONE", "NONE", "GRID", "NONE")
                # Process: Shift (2)
                arcpy.Shift_management(temp2, moyenne_5_5, "0", "-9", "")
                print('calcul de la moyenne en fenetre 5*5: OK')
                        
                # Process: Focal Statistics Std 5/5
                arcpy.gp.FocalStatistics_sa(image, temp1, "Rectangle 5 5 CELL", "STD", "DATA")
                # Process: Copy Raster (3)
                arcpy.CopyRaster_management(temp1, temp2, "", "", "-3,402823e+038", "NONE", "NONE", "8_BIT_UNSIGNED", "NONE", "NONE", "GRID", "NONE")
                # Process: Shift (3)
                arcpy.Shift_management(temp2, ecartype_5_5, "9", "-9", "")
                print('calcul de l''ecart-type en fenetre 5*5: OK')
                
                # Process: Raster To Geodatabase (multiple)\\on importe les rasters dans la geodatase
                #arcpy.RasterToGeodatabase_conversion("image_temp;'C:\\Mini-Projet\\mini_projet6\\moyenne_3_3';'C:\\Mini-Projet\\mini_projet6\\moyenne_5_5';'C:\\Mini-Projet\\mini_projet6\\ecartype_5_5'", Geodatabase, "")

                # Process: Mosaic To New Raster
                arcpy.MosaicToNewRaster_management("image_temp;moyenne_3_3;moyenne_5_5;ecartype_5_5", Geodatabase, "image_sortie", "", "8_BIT_UNSIGNED", "", "1", "LAST", "FIRST")
                print('opération finie')
